/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ChanceSnow' at '10/13/16 1:18 PM' with Gradle 3.1
 *
 * @author ChanceSnow, @date 10/13/16 1:18 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
