/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'ChanceSnow' at '10/13/16 1:18 PM' with Gradle 3.1
 *
 * @author ChanceSnow, @date 10/13/16 1:18 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
